# Shopify App Configuration
name = "Gang Sheet Builder By USA"
client_id = "fe2fa282682645ed90c6538ddf50f0e4"
application_url = "https://app.gsb-engine.dev"
embedded = true

[access_scopes]
scopes = "read_orders,write_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://app.gsb-engine.dev/shopify/embedded",
  "https://app.gsb-engine.dev/api/auth/callback"
]

[webhooks]
api_version = "2025-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = false

# App Proxy - Customer storefront access
[app_proxy]
url = "https://app.gsb-engine.dev"
subpath = "gsb"
prefix = "apps"

# Extensions
extension_directories = ["extensions/gsb-embed"]
