api_version = "2024-10"
type = "ui_extension"
name = "Design Preview"
handle = "checkout-design-preview"

[[targeting]]
target = "purchase.checkout.block.render"

[settings]
[[settings.fields]]
key = "title"
type = "single_line_text_field"
name = "Section Title"

[[settings.fields]]
key = "show_dimensions"
type = "boolean"
name = "Show Dimensions"

[[settings.fields]]
key = "show_edit_button"
type = "boolean"
name = "Show Edit Button"

[[settings.fields]]
key = "show_download_button"
type = "boolean"
name = "Show Download Button"
