import type { TemplateDefinition } from "../types";

/** Seed records to hydrate template gallery for local development */
export function sampleTemplates(): TemplateDefinition[] {
  const now = Date.now();
  return [
    {
      id: "sup-tshirt-front-1",
      title: "Basic Tee Front",
      description: "Chest logo with editable headline",
      tags: ["tshirt", "front", "logo"],
      createdBy: "super",
      target: { productSlug: "tshirt", surfaceId: "tshirt-front" },
      defaultPrintTech: "dtf",
      thumbDataUrl: undefined,
      createdAt: now - 2000,
      placeholders: [
        {
          key: "headline",
          label: "Brand headline",
          type: "text",
          description: "Primary line of text shown across the chest.",
          required: true,
          lockFont: true,
          maxLength: 24,
          minLength: 3,
          initialValue: "YOUR BRAND",
          allowedFonts: ["Inter", "Poppins", "Montserrat"],
          notes: "Keep it short for best readability on DTF transfers.",
        },
      ],
      items: [
        {
          id: "i1",
          kind: "rect",
          name: "Guide",
          x: 500,
          y: 160,
          width: 400,
          height: 400,
          rotation: 0,
          visible: true,
          locked: false,
          fill: "#f5f5f5",
          stroke: "#888",
          strokeWidth: 1,
          opacity: 1,
          dash: [4, 4],
          template: {
            sourceTemplateId: "sup-tshirt-front-1",
            lockPosition: true,
            lockSizing: true,
            lockStyle: true,
            preventDeletion: true,
          },
        },
        {
          id: "i2",
          kind: "text",
          name: "Headline",
          x: 520,
          y: 200,
          width: 360,
          height: 60,
          rotation: 0,
          visible: true,
          locked: false,
          text: "YOUR BRAND",
          fontSize: 42,
          fontFamily: "Inter, Arial",
          fill: "#111",
          align: "center",
          shadowColor: "rgba(0,0,0,0)",
          shadowBlur: 0,
          stroke: "#000",
          strokeWidth: 0,
          opacity: 1,
          template: {
            sourceTemplateId: "sup-tshirt-front-1",
            lockPosition: true,
            placeholder: {
              key: "headline",
              label: "Brand headline",
              type: "text",
              required: true,
              lockFont: true,
              maxLength: 24,
              minLength: 3,
              initialValue: "YOUR BRAND",
              allowedFonts: ["Inter", "Poppins", "Montserrat"],
            },
          },
        },
      ],
    },
    {
      id: "sup-mug-wrap-1",
      title: "Mug Wrap Quote",
      description: "Full wrap quote for sublimation mugs",
      tags: ["mug", "wrap", "quote"],
      createdBy: "super",
      target: { productSlug: "mug", surfaceId: "mug-wrap" },
      defaultPrintTech: "sublimation",
      thumbDataUrl: undefined,
      createdAt: now - 1000,
      placeholders: [
        {
          key: "quote",
          label: "Quote text",
          type: "text",
          description: "Wrap-around quote or slogan",
          required: true,
          maxLength: 64,
          initialValue: "But first, coffee ?",
        },
      ],
      items: [
        {
          id: "m1",
          kind: "text",
          name: "Quote",
          x: 200,
          y: 250,
          width: 600,
          height: 60,
          rotation: 0,
          visible: true,
          locked: false,
          text: "But first, coffee ?",
          fontSize: 36,
          fontFamily: "Inter, Arial",
          fill: "#333",
          align: "center",
          shadowColor: "rgba(0,0,0,0)",
          shadowBlur: 0,
          stroke: "#000",
          strokeWidth: 0,
          opacity: 1,
          template: {
            sourceTemplateId: "sup-mug-wrap-1",
            lockPosition: true,
            placeholder: {
              key: "quote",
              label: "Quote text",
              type: "text",
              required: true,
              maxLength: 64,
              initialValue: "But first, coffee ?",
            },
          },
        },
      ],
    },
    {
      id: "mer-cap-front-1",
      title: "Cap Front Logo",
      tags: ["cap", "front", "logo"],
      createdBy: "merchant",
      merchantId: "demo-merchant",
      target: { productSlug: "cap", surfaceId: "cap-front" },
      defaultPrintTech: "embroidery",
      thumbDataUrl: undefined,
      createdAt: now - 500,
      placeholders: [
        {
          key: "capLogo",
          label: "Cap logo",
          type: "text",
          description: "Short brand mark for the cap front",
          required: true,
          lockFont: true,
          maxLength: 8,
          initialValue: "ACME",
        },
      ],
      items: [
        {
          id: "c1",
          kind: "text",
          name: "Cap Logo",
          x: 560,
          y: 220,
          width: 280,
          height: 60,
          rotation: 0,
          visible: true,
          locked: false,
          text: "ACME",
          fontSize: 48,
          fontFamily: "Inter, Arial",
          fill: "#000",
          align: "center",
          shadowColor: "rgba(0,0,0,0)",
          shadowBlur: 0,
          stroke: "#000",
          strokeWidth: 0,
          opacity: 1,
          template: {
            sourceTemplateId: "mer-cap-front-1",
            lockPosition: true,
            placeholder: {
              key: "capLogo",
              label: "Cap logo",
              type: "text",
              required: true,
              lockFont: true,
              maxLength: 8,
              initialValue: "ACME",
            },
          },
        },
      ],
    },
  ];
}
